#!/bin/bash

export APP_SECRET_KEY="YOURCOOLACCESSTOKEN"
export ADMIN_TOKEN="YOURCOOLACCESSTOKEN"
export DB_USER="YOURCOOLACCESSTOKEN"
export DB_PASSWORD="YOURCOOLACCESSTOKEN"
export DB_STRING="YOURCOOLACCESSTOKEN"

echo "Pronto para começar"